### ISSUE TITLE
How do I use Lorem Pixel in Brackets?

### ISSUE THREAD

**Issue by netsi1964** [dnbard/brackets-lorem-pixel#1]
Hi,
I have installed your Lorem Pixel but simply cannot find out how to use it :-)
Could you please write a description of how to use inside Brackets?
- Thanks.
/Sten

**Comment by djlotus** [comment]
The icon is not showing up for me either. 

 OS X 10.9.5
Brackets Release 1.1 build 1.1.0-15558 (release ea908cae5) 

I can hover over where the icon is supposed to be and use the extension with no problems. Just the icon is not showing up.

![screen shot 2015-02-07 at 6 06 10 pm](https://cloud.githubusercontent.com/assets/8974239/6094358/406a70a0-aef5-11e4-91b0-630ba3fbd063.jpg)
